### ISSUE TITLE
Selecting "Inputs (this game)" crashes Retroarch on Android

### ISSUE THREAD

**Issue by PKstarship** [libretro/mame2010-libretro#121]
Pretty much the title, it also seems to affect the player controls options inside "Inputs (general)" too. Rather frustrating of course, as one game I would like to play requires me to map controls to make it work properly.

Playing on Mame 2010 0.139 70732f9 (the latest version available in core downloads at this time) and OS is Android 7.0, if it helps.

**Comment by abuchanan920** [comment]
Same behavior on Raspberry Pi 4.

I’m seeing an “Unhandled fault: alignment exception (0xa21) at 0x<varies from run to run>”
