### ISSUE TITLE
License

### ISSUE THREAD

**Issue by guoyunhe** [libretro/mame2010-libretro#137]
I am packaging MAME cores for openSUSE Linux. You may know that most Linux distributions have their license guidelines. The package need to correctly indicate its license.

I read this blog post: https://www.mamedev.org/?p=422

So **MAME** core is GPL/BSD licensed. :heavy_check_mark: 

**MAME 2000** and **MAME 2010** don't have a license in the repo. :question: 

**MAME 2003** and **MAME 2003+** have a custom license. Are they FOSS or freeware :question:

**Comment by hizzlekizzle** [comment]
Every MAME prior to circa March 2016 uses the custom MAME license, which is noncommercial, "nonfree"/source-available.

**Comment by guoyunhe** [comment]
@hizzlekizzle thanks for information!
