### ISSUE TITLE
Mame loads startrek.zip in wrong orientation and will not recognize rom-specific cfg files.

### ISSUE THREAD

**Issue by rawlangs** [libretro/mame2010-libretro#15]
Mame automatically rotates startrek.zip 90 degrees clockwise.  I can use rgui to manually rotate, but I can't make this setting "stick".  I have created startrek.zip.cfg and placed it in the ROM directory.  This file rotates startrek.zip when loaded in lr-mame2003, but lr-mame2010 does not recognize this file.

I would like startrek.zip to load in the correct orientation, and I would like lr-mame2010 to recognize rom-specific cfg files like other libretro cores.

**Comment by markwkidd** [comment]
Hi @rawlangs if you compile mame2010 from source now I have updated the paths where mame2010 loads its various assets, including the `cfg` path. I believe his may resolve your issue with mame2010 not recognizing game-specific `cfg` files.
