### ISSUE TITLE
Player 2 X-Arcade buttons 5 and 6

### ISSUE THREAD

**Issue by jyan21** [libretro/mame2010-libretro#21]
Not sure if it only happens to the X-Arcade controller, but I've seen many posts regarding the player 2 buttons 5 and 6 not working.  Both buttons can be configured in RetroArch but does not register in game like all the other buttons.

**Comment by FelipeVeiga** [comment]
same problem here.

**Comment by markwkidd** [comment]
This is because MAME 0.139 doesn't come with default keyboard mappings for those P2 buttons. It should be possible to properly implement defaults for those buttons in mame2010, however. I didn't immediately see where to make this change but I'll try to take a longer look in the future.

**Comment by markwkidd** [comment]
You should be able to work around this in the meantime by use of the MAME Tab Menu

**Comment by markwkidd** [comment]
I've found the place to fix this: https://github.com/libretro/mame2010-libretro/blob/master/src/emu/inpttype.h#L139-L140

I will need to make sure there are some unassigned keyboard keys available before I put in default mappings for those two, however
