### ISSUE TITLE
Makefile.libretro missing and other problems

### ISSUE THREAD

**Issue by Roet-Ivar** [libretro/mame2010-libretro#23]
Hi sir.
I'm trying to build your repo but I don't get far (I'm a beginner in linux environments).

Firstly, running the make command: 
make -f Makefile.libretro "VRENDER=soft" "NATIVE=1" buildtools
Makefile.libretro: this file doesn't seem to exist, or am I missing something basic here?

Same goes for:
make -f Makefile.libretro "VRENDER=soft" "platform=android" emulator -j4

Thanks for any help!

EDIT: It seems like building w/o "Makefile" and "platform" argument works for the emulator, but "platform=android" gives a bunch of "file does not exist" errors, even though they seem to be there

**Comment by twinaphex** [comment]
you need to use the regular Makefile instead.

**Comment by Roet-Ivar** [comment]
So I tried: make -f Makefile "VRENDER=soft" "platform=android" emulator -j4

```
mkdir -p obj/retro64/mame/drivers
mkdir: kan inte skapa katalog ”obj/retro64/mame/drivers”: No such file or directory
make: [obj/retro64/mame/drivers] Fel 1 (ignoreras)
Assembler messages:
Fatal error: Assembler messages:
Fatal error: can't create obj/retro64/mame/drivers/albazc.o: No such file or directory
Fatal error: can't create obj/retro64/mame/drivers/rmhaihai.o: No such file or directory

Assembler messages:
Fatal error: can't create obj/retro64/mame/drivers/albazg.o: No such file or directory
In file included from ./src/emu/emu.h:53:0,
                 from src/mame/drivers/albazc.c:13:
./src/emu/emucore.h:25:21: fatal error: exception: No such file or directory
compilation terminated.
make: *** [obj/retro64/mame/drivers/albazc.o] Fel 2
make: *** Inväntar oavslutade jobb...In file included from ./src/emu/emu.h:53:0,
                 from src/mame/drivers/albazg.c:56:
./src/emu/emucore.h:25:21: fatal error: exception: No such file or directory
compilation terminated.

make: *** [obj/retro64/mame/drivers/albazg.o] Fel 2
In file included from ./src/emu/emu.h:53:0,
                 from src/mame/drivers/rmhaihai.c:31:
./src/emu/emucore.h:25:21: fatal error: exception: No such file or directory
compilation terminated.
make: *** [obj/retro64/mame/drivers/rmhaihai.o] Fel 2
In file included from ./src/emu/emu.h:53:0,
                 from src/mame/mamedriv.c:18:
./src/emu/emucore.h:25:21: fatal error: exception: No such file or directory
compilation terminated.
make: *** [obj/retro64/mame/mamedriv.o] Fel 1
```

**Comment by Roet-Ivar** [comment]
Is there a binary that I could download instead? I'm too stupid for this. Thanks!

**Comment by Roet-Ivar** [comment]
OK. So I decided to give this another shot to learn something, even though I found a binary floating around.
Is there anyone who could try build this project and tell me what's going on with the toolchain setup and the errors from my logout above? Would highly appreciate this!

**Comment by r-type** [comment]
you have to first setup an android standalone toolchain.

you can find info here https://developer.android.com/ndk/guides/standalone_toolchain.html

old ndk
```
make-standalone-toolchain.sh --toolchain=arm-linux-androideabi-4.9 --platform=android-21 --install-dir=/tmp/android-stdtc
```
newer ndk
```
 make_standalone_toolchain.py --arch arm --api 21 --install-dir /tmp/android-stdtc
```
when you are done with your standalone tc ,
add it to your path 
```
export PATH=$PATH:/tmp/android-stdtc/bin
```
and  just type
```
make platform=android -j4
```
btw it failed to build also for me until
I tweak makefile.common to add -I$(SRC_DIR)/mame , in INCFLAGS declaration
```
	-I$(SRC_DIR)/osd/retro \
	-I$(SRC_DIR)/mame 
```
and in makefile to add PTR64 = 0 , in platform android section
```
# Android 
else ifeq ($(platform), android)
PTR64 = 0
```

**Comment by Roet-Ivar** [comment]
@r-type Thank you so much sir! Can't wait to test this out when I get home. By the way, is there any gain of compiling this for ARM64 (using Nvidia Shield TV)? obliviously I don't know exactly what I'm talking about =)

**Comment by r-type** [comment]
never tried a 64 build , 
but i think you have to make an arm64 standalone tc 
make_standalone_toolchain.py  --arch arm64
and put PTR64=1 instead of PTR64=0 in android platform section in the makefile.

**Comment by Roet-Ivar** [comment]
@r-type I'll report back with results! Hopefully I can finally get this to build so I can turn off nag-screen/game info/warnings and rotation of some games.

**Comment by Roet-Ivar** [comment]
@r-type I still fail when trying to compile :(
```
compilation terminated.
make: *** [src/obj/mame/drivers/albazc.o] Fel 1
make: *** [src/obj/mame/drivers/albazg.o] Fel 1
In file included from ./src/emu/emu.h:53:0,
                 from src/mame/drivers/rmhaihai.c:31:
./src/emu/emucore.h:25:21: fatal error: exception: No such file or directory
```
I feel like your suggestions are related to the issue with including paths, just can't figure it out.

**Comment by r-type** [comment]
nice it works,
yes it's an old port then maybe  mess in the ccomflags .

**Comment by Roet-Ivar** [comment]
@r-type The 64bit build did not work, not so surprising since I have no idea what the impact is when removing those flags =)

An off topic question: Do you know why vertical games (like 1941 - 1943 etc) rotates to the side? (I guess these values are usally read from the gamelist.xml)
Could "rotate = 1" in mame.ini be the cause for that? 
Since I'm using a TV I don't want games to rotate at all. Thanks for all of your help!

**Comment by r-type** [comment]
don't know , maybe some other user having good knowledge with mame.ini like @Tatsuya79 can answer to this.

**Comment by Tatsuya79** [comment]
I'm not sure what is the behaviour in mame2010 as I'm not using this core.
But you should be able to create a vertical.ini in system\mame2010\ini\ with "ror 1" to rotate vertical games.

**Comment by twinaphex** [comment]
You don't want MAME to apply rotation and scaling itself. We should get rid of all that junk code in MAME 2010.

It's the frontend (RetroArch in this case) that should do scaling and rotation, not this MAME core.  There's an environment callback which you can use which can inform the frontend what rotation setting the frontend should use for this/that game. That is what we should be looking into.

We don't want MAME to do rotation/scaling itself since we know that it will be slower and inoptimal compared to what the frontend could do, it's best left up to the frontend.

For mainline MAME though it's a different story and we can leave this up to MAME, but for MAME 2010 and 2014 though, we should be slimlining these MAME versions and making them less inoptimal vs. plain-jane MAME.

**Comment by sunshineoflife** [comment]
@r-type 
Hi sir.
I'm trying to build this repo by NDK build system , not using a standalone toolchain. 
My environments is ndk-r10e in windows 7. 
When i use the command `ndk-build`, it seems not work. No source file is compiled.
Is there anyone who could try build this project by NDK tools.

**Comment by bparker06** [comment]
@sunshineoflife Mame2010 for Android is now available through the online updater in RetroArch.

**Comment by markwkidd** [comment]
@Roet-Ivar do you consider this issue resolved? If so, could you please close it?

**Comment by Roet-Ivar** [comment]
Since the mame 2010 is now included in retroarch I find this issue resolved.
