### ISSUE TITLE
Issues building on Pi

### ISSUE THREAD

**Issue by Eddiiie** [libretro/mame2010-libretro#32]
Hi,
Following the readme.txt, it says 
---------------
 build for pc linux/win:

     make -f Makefile.libretro "VRENDER=soft" -j4 buildtools
     make -f Makefile.libretro "VRENDER=soft" -j4

---------------

But there is no Makefile.libretro file available.

Using the Makefile that is present,  (Makefile)  after hours of grinding, it comes to a halt with the following message:
{standard input}: Assembler messages:
{standard input}:1643: Warning: end of file not at end of a line; newline inserted
{standard input}:2835: Error: junk at end of line, first unrecognized character is `c'
{standard input}:2835: Warning: ignoring changed section attributes for .text._Z10fatalerrorPKcz
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:686: recipe for target 'obj/retro/emu/cpu/tms57002/tms57002.o' failed
make: *** [obj/retro/emu/cpu/tms57002/tms57002.o] Error 4
pi@raspberrypi:~/mame0139/mame2010-libretro-master $

I will try again using Makefile.common

?

**Comment by Eddiiie** [comment]
Makefile.common errored immediately

pi@raspberrypi:~/mame0139/mame2010-libretro-master $ make -f Makefile.common
make: *** No rule to make target '/mame/machine/nmk112.o', needed by '/mame/shared.a'.  Stop.

**Comment by r-type** [comment]
Just use make  VRENDER=soft , (there is a Makefile) , if you are unsure you can lookat the recipes on the libretro-super .

now  for you build problem , it seem your gcc crash a compiling tms57002.  too much resource for it.
 you can try to build this file on a pc host using a crosscompiler 
or trying to build it a -O0 (just recopy the line above the crash g++ ... and change -O2 or -O3 with -00 for this file.

**Comment by Eddiiie** [comment]
Ok, I went and did a make VRENDER=soft   .......   hours later, new error -

src/osd/retro/retrowork.c: In function ‘int osd_work_queue_wait(osd_work_queue*, osd_ticks_t)’:
src/osd/retro/retrowork.c:264:26: error: ‘osd_yield_processor’ was not declared in this scope
      osd_yield_processor();
                          ^
src/osd/retro/retrowork.c: In function ‘int osd_work_item_wait(osd_work_item*, osd_ticks_t)’:
src/osd/retro/retrowork.c:499:25: error: ‘osd_yield_processor’ was not declared in this scope
     osd_yield_processor();
                         ^
src/osd/retro/retrowork.c: In function ‘void* worker_thread_entry(void*)’:
src/osd/retro/retrowork.c:650:27: error: ‘osd_yield_processor’ was not declared in this scope
       osd_yield_processor();
                           ^
Makefile:686: recipe for target 'obj/retro/osd/retro/retrowork.o' failed
make: *** [obj/retro/osd/retro/retrowork.o] Error 1
pi@raspberrypi:~/mame0139/mame2010-libretro-master $



---------

Note, I did not fix build problem mentioned in last reply, as it did not crash the same way.

**Comment by bparker06** [comment]
That is the same error we get trying to build for armhf on the buildbot... I have no idea why but I haven't really looked into it more. I should also note that adding PTR64=0 to the make line is probably also necessary for 32-bit targets.

**Comment by r-type** [comment]
https://github.com/libretro/mame2010-libretro/blob/master/src/osd/retro/osinline.h
#if defined(ARM_ENABLED) this should fix the above error.

You meed at first this for arm based device.
Also maybe lookat all the ifdef ANDROID if other error .
I think l about the delegate.

**Comment by Eddiiie** [comment]
osinline.h is different..

GIT says: 
```
#endif /* __ppc64__ || __PPC64__ */

#endif

#if defined(ARM_ENABLED)

#ifndef YieldProcessor

```
Mine says:
```
#define osd_exchange64 _osd_exchange64
#endif /* __x86_64__ */
#elif defined(__ppc__) || defined (__PPC__) || defined(__ppc64__) || defined(__$
#define osd_yield_pocessor() __asm__ __volatile__ ( " nop \n nop \n" )
#if defined(__ppc64__) || defined(__PPC64__)
#define _osd_exchange64(ptr, exchange) (register INT64 ret; __asm__ __volatile_$
#define osd_exchange64 _osd_exchange64
#endif /* __ppc64__ || __PPC64__ */
#else

#ifndef YieldProcessor
#define YieldProcessor() do {} while (0)
#define osd_yield_processor() YieldProcessor()
#endif
#endif
```

I will make it -
```
#endif /* __ppc64__ || __PPC64__ */
#else

#if defined(ARM_ENABLED)

#ifndef YieldProcessor
#define YieldProcessor() do {} while (0)
#define osd_yield_processor() YieldProcessor()
#endif
#endif
```

**Comment by Eddiiie** [comment]
nope.

```
In file included from src/osd/eminline.h:25:0,
                 from src/emu/emu.h:25,
                 from src/mame/mame.c:12:
src/osd/retro/osinline.h:10:0: error: unterminated #ifndef
 #ifndef __OSINLINE__

```

**Comment by Eddiiie** [comment]
Grabbed the version from GIT, made old file osinline.h.old
building.

**Comment by Eddiiie** [comment]
My osinline.h file has his already.

...
#if defined(ARM_ENABLED) 
...

**Comment by bparker06** [comment]
I hardcoded ARM_ENABLED=1 and also fixed a linker issue when building for arm platforms, I still have one more linker issue but hopefully it will work after that.

**Comment by bparker06** [comment]
It should start building for armhf successfully now, let me know if it works.

**Comment by Eddiiie** [comment]
It builds!! Thanks!
