### ISSUE TITLE
retroarch crashes loading mame2010 content in windows 10 x64

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2010-libretro#34]
I'm working with a fresh install of the latest nightly RetroArch in Windows 10 x64. I'm working with the MAME 2010 core downloaded from the online updater.

When I try to launch content, the entire RetroArch application crashes. MAME 2003 works as expected with the same installation.

The ROMset file in question, term2, runs as expected in standalone MAME 0.139. 

Here is the log output up until the crash: https://pastebin.com/W2EU0BhD

Edit: should this be a RetroArch bug instead of a MAME 2010 bug? Both?

**Comment by keithallenjackson** [comment]
I have the same problem.

**Comment by dominater01** [comment]
im having the same issue im using retroarch 1.6.3 installer version and retroarch just crashes

**Comment by Quickgold74** [comment]
Same problem here :(

**Comment by r-type** [comment]
does this one work for you ? 
https://ufile.io/jwk7n

**Comment by Quickgold74** [comment]
Thanks @r-type now it works, was the core compiled by you? or is it an older version? I ask because, I belive  that in the download page there should be a section with stable cores (like the RA stable)  and not the nightly versions only.

**Comment by r-type** [comment]
Crossbuild with the last commit.
The buildbot should have it now.

**Comment by markwkidd** [comment]
@r-type Looks good here in Windows 10 x64. Thank you!
