### ISSUE TITLE
Core mapping missing

### ISSUE THREAD

**Issue by UDb23** [libretro/mame2010-libretro#39]
Input mapping option is missing from the Quick menu and core input mapping is not available.

**Comment by markwkidd** [comment]
@UDb23 could you clarify what you mean? I'm attaching a screenshot of what I see in the Quick Menu. Maybe this has already been fixed?

![screenshot 2018-03-05 11 43 58](https://user-images.githubusercontent.com/19554678/36987574-a9b30114-206a-11e8-9ca9-815745e8fac4.png)

**Comment by UDb23** [comment]
Thanks for checking this.
I mean[this](https://github.com/retropie/retropie-setup/wiki/RetroArch-Configuration#core-input-remapping).  I found it's (or was) missing on Retropie on the Pi.  
Your screenshot is from the windows version; not sure this also means it's now available on the Pi (retropie/raspbian) version too. Unfortunately currently I cannot access my Pi to check if meanwhile it has been fixed.
Can you save a core remap file in the win version ?

**Comment by markwkidd** [comment]
Any options that show up in the XMB interface should also show up in the RGUI interface that RetroPie refers to in those docs. I'm having no trouble saving a core remap right now either.

Note: inputs for players 3-5 aren't working right yet. hopefully soon.
