### ISSUE TITLE
Building From Source fails (Readme.txt not found)

### ISSUE THREAD

**Issue by estefan3112** [libretro/mame2010-libretro#93]
While I was successful in building lr-MAME2010 with sample support, the actual installation of the emulator fails on Linux:
= = = = = = = = = = = = = = = = = = = = =
Installing 'lr-mame2010' : Arcade emu - MAME 0.139 port for libretro
= = = = = = = = = = = = = = = = = = = = =

'/home/pi/RetroPie-Setup/tmp/build/lr-mame2010/mame2010_libretro.so' -> '/opt/retropie/libretrocores/lr-mame2010/mame2010_libretro.so'
~
Could not successfully install Arcade emu - MAME 0.139 port for libretro (/home/pi/RetroPie-Setup/tmp/build/lr-mame2010/README.txt not found).

On my Raspberry Pi, the installation was nevertheless successful (probably because the README.txt was already there from the binary installation. In Ubuntu 16.04, where the Core is built from source, the installation failed. I guess that this is just a small issue.

**Comment by estefan3112** [comment]
[rps_2018-02-22_183943.log.gz](https://github.com/libretro/mame2010-libretro/files/1749216/rps_2018-02-22_183943.log.gz)

**Comment by markwkidd** [comment]
Thanks for the report @estefan3112 ! This one is a downstream is a retropie-setup issue. I've filed a PR there if you don't mind closing the issue here. RetroPie-Setup PR: https://github.com/RetroPie/RetroPie-Setup/pull/2308
