### ISSUE TITLE
call_notifiers(MACHINE_NOTIFY_EXIT) is never called / no graceful exit

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2010-libretro#95]
I'm working to add hiscore functionality to this core.

In the process of hooking up the hiscore save system, I have discovered that [call_notifiers(MACHINE_NOTIFY_EXIT) in /src/emu/machine.c](https://github.com/libretro/mame2010-libretro/blob/master/src/emu/machine.c#L413) is never being called. 

This seems to be a bug. There are a number of important-looking deallocation and graceful-exit functions registered as callbacks there, including `osd_exit()` in `retromain.c`.

From my investigation it seems like the right flag is being set to signal the exit, but maybe the MAME emulation loop never gets executed again after that flag is set, so the flag is never acted upon.

In the case of hiscore, this means that the memory maps for hiscore saves are never written to disk when the emulator shuts down. I could hack around this problem and trigger the high scores save another way but it seems better to try to fix MACHINE_NOTIFY_EXIT.

So far I have found a dozen ways to make mame2010 crash while trying to fix this, but I'm working from ignorance. @r-type if you have time, do you have any insight on this part of MAME or mame2010?

**Comment by r-type** [comment]
the call is here in void running_machine::retro_loop()
https://github.com/libretro/mame2010-libretro/blob/master/src/emu/machine.c#L468

**Comment by markwkidd** [comment]
@r-type that part of retro_loop() never seems to be executed. Hmm.

**Comment by r-type** [comment]
so try to add 
      call_notifiers(MACHINE_NOTIFY_EXIT);
here 
https://github.com/libretro/mame2010-libretro/blob/master/src/emu/machine.c#L430

it is call at  retro_deinit(void)

https://github.com/libretro/mame2010-libretro/blob/67ec340d5fe2cf7ce9a1066520465a157a465798/src/osd/retro/retromain.c#L768

**Comment by r-type** [comment]
it is what i have done for 2014 and later
https://github.com/libretro/mame2014-libretro/blob/master/src/emu/machine.c#L410

**Comment by markwkidd** [comment]
I moved the `call_notifiers` call to `retro_machineexit()`, which unfortunately crashes mame2010 and retroarch now when close content is selected from the RA Quick Menu

https://github.com/markwkidd/mame2010-libretro/blob/notify-exit-fix/src/emu/machine.c#L425

:hammer: :hammer:

**Comment by r-type** [comment]
did you put it in line 431 after config_save_settings(this); ???

**Comment by markwkidd** [comment]
You are right, I did not have those calls in the right sequence.  Once I put the new line after config_save_settings(this); the exit notification system seems to be working fine.

Hopefully this is all I still need in order to implement the hiscore patch. Thank you!

**Comment by markwkidd** [comment]
Closed via https://github.com/libretro/mame2010-libretro/pull/99
